language: r
cache:
  - $HOME/.ccache
  - packages
cran: https://cloud.r-project.org
env:
  global:
    - CRAN_REPO=https://cloud.r-project.org
jobs:
  include:
  - os: linux
    dist: xenial
    r: oldrel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - gdal-bin
          - libgdal-dev
          - libgeos-dev
          - libgit2-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - unrar
    services:
      - xvfb
    r_packages:
      - rgdal
      - rgeos
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
  - os: linux
    dist: xenial
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - gdal-bin
          - libgdal-dev
          - libgeos-dev
          - libgit2-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - unrar
    services:
      - xvfb
    r_packages:
      - covr
      - devtools
      - rgdal
      - rgeos
    r_github_packages:
      - jimhester/lintr
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
    after_success:
    - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: xenial
    r: devel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - gdal-bin
          - libgdal-dev
          - libgeos-dev
          - libgit2-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - unrar
    services:
      - xvfb
    r_packages:
      - devtools
      - rgdal
      - rgeos
  - os: osx
    osx_image: xcode9.4
    r: oldrel
    addons:
      homebrew:
        packages:
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
  - os: osx
    osx_image: xcode11.4
    r: release
    addons:
      homebrew:
        packages:
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
